import { 
  Branch, 
  Barber, 
  ServiceItem, 
  BookingAppointment, 
  Customer, 
  Expense, 
  BarberWithdrawal,
  AdminUser 
} from './types';

export const DEFAULT_ADMIN: AdminUser = {
  role: 'admin',
  id: 'admin-1',
  name: 'Admin',
  email: 'admin@blackbox.ge',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
};

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'marjane',
    name: 'Marjanishvili Branch',
    shortName: 'Marjane',
    address: 'Sankt-Petersburgs St, 2A',
    barberCount: 6,
    initialCashDrawer: 350.00,
  },
  {
    id: 'dighomi',
    name: 'Dighomi Branch',
    shortName: 'Dighomi',
    address: 'Robakidze Ave, 7',
    barberCount: 3,
    initialCashDrawer: 200.00,
  },
  {
    id: 'saburtalo',
    name: 'Saburtalo Branch',
    shortName: 'Saburtalo',
    address: 'Pekini Ave, 22',
    barberCount: 3,
    initialCashDrawer: 250.00,
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  { 
    id: 's1', 
    name: 'Hair + Beard', 
    price: 45, 
    duration: 45,
    isTbd: false
  },
  { 
    id: 's2', 
    name: 'Hydrofacial', 
    price: null, 
    duration: 45,
    isTbd: true 
  },
  { 
    id: 's3', 
    name: 'Hydromassage', 
    price: null, 
    duration: 30,
    isTbd: true 
  },
];

export const INITIAL_BARBERS: Barber[] = [
  // -------------------------------------------------------------
  // Marjane — 6 employees
  // -------------------------------------------------------------
  { 
    id: 'b1', 
    name: 'Barber #1', 
    branchId: 'marjane', 
    specialty: 'Master Stylist & Skin Fades', 
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80', 
    workingHours: 8, 
    commissionRate: 0.5,
    monthBaseEarnings: 1450,
    pin: '1234'
  },
  { 
    id: 'b2', 
    name: 'Barber #2', 
    branchId: 'marjane', 
    specialty: 'Beard Art & Razor Lineups', 
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80', 
    workingHours: 8, 
    commissionRate: 0.5,
    monthBaseEarnings: 1680,
    pin: '1234'
  },
  { 
    id: 'b3', 
    name: 'Barber #3', 
    branchId: 'marjane', 
    specialty: 'Classic Scissor Cuts', 
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80', 
    workingHours: 8, 
    commissionRate: 0.5,
    monthBaseEarnings: 1220,
    pin: '1234'
  },
  { 
    id: 'b4', 
    name: 'Barber #4', 
    branchId: 'marjane', 
    specialty: 'Texture & Hot Towel Shave', 
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80', 
    workingHours: 7, 
    commissionRate: 0.5,
    monthBaseEarnings: 980,
    pin: '1234'
  },
  { 
    id: 'b5', 
    name: 'Barber #5', 
    branchId: 'marjane', 
    specialty: 'Taper Fade & Beard Sculpting', 
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80', 
    workingHours: 8, 
    commissionRate: 0.5,
    monthBaseEarnings: 1100,
    pin: '1234'
  },
  { 
    id: 'b6', 
    name: 'Barber #6', 
    branchId: 'marjane', 
    specialty: 'Modern Crop & Hair Styling', 
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80', 
    workingHours: 6, 
    commissionRate: 0.5,
    monthBaseEarnings: 840,
    pin: '1234'
  },

  // -------------------------------------------------------------
  // Dighomi — 3 employees
  // -------------------------------------------------------------
  { 
    id: 'b7', 
    name: 'Barber #7', 
    branchId: 'dighomi', 
    specialty: 'Master Barber & Precision Fades', 
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80', 
    workingHours: 8, 
    commissionRate: 0.5,
    monthBaseEarnings: 1310,
    pin: '1234'
  },
  { 
    id: 'b8', 
    name: 'Barber #8', 
    branchId: 'dighomi', 
    specialty: 'Beard Grooming & Shape', 
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80', 
    workingHours: 7, 
    commissionRate: 0.5,
    monthBaseEarnings: 1040,
    pin: '1234'
  },
  { 
    id: 'b9', 
    name: 'Barber #9', 
    branchId: 'dighomi', 
    specialty: 'Skin Fade Pro & Hot Shave', 
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80', 
    workingHours: 8, 
    commissionRate: 0.5,
    monthBaseEarnings: 1150,
    pin: '1234'
  },

  // -------------------------------------------------------------
  // Saburtalo — 3 employees
  // -------------------------------------------------------------
  { 
    id: 'b10', 
    name: 'Barber #10', 
    branchId: 'saburtalo', 
    specialty: 'Senior Stylist & Scissor Work', 
    avatar: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=120&auto=format&fit=crop&q=80', 
    workingHours: 8, 
    commissionRate: 0.5,
    monthBaseEarnings: 1250,
    pin: '1234'
  },
  { 
    id: 'b11', 
    name: 'Barber #11', 
    branchId: 'saburtalo', 
    specialty: 'Modern Cuts & Sharp Lineups', 
    avatar: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=120&auto=format&fit=crop&q=80', 
    workingHours: 7, 
    commissionRate: 0.5,
    monthBaseEarnings: 990,
    pin: '1234'
  },
  { 
    id: 'b12', 
    name: 'Barber #12', 
    branchId: 'saburtalo', 
    specialty: 'Hot Towel Treatment & Beard Art', 
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80', 
    workingHours: 8, 
    commissionRate: 0.5,
    monthBaseEarnings: 1120,
    pin: '1234'
  },
];

export const INITIAL_BOOKINGS: BookingAppointment[] = [
  // -------------------------------------------------------------
  // Marjane Appointments
  // -------------------------------------------------------------
  // 1. Scheduled (on-time)
  {
    id: 'bk-1',
    ticketNumber: '#MB-101',
    branchId: 'marjane',
    customerName: 'Davit Kipiani',
    customerPhone: '+995 599 123 456',
    isStudent: false,
    allergies: 'None',
    barberId: 'b1',
    barberName: 'Barber #1',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 0,
    discountAmount: 0,
    price: 45,
    time: '14:00',
    source: 'Instagram',
    type: 'booking',
    status: 'Scheduled',
    createdAt: 'Today, 10:15',
    isNoShowGraceExpired: false,
  },
  // 2. Scheduled (Past 10-minute grace period -> Flagged for No-Show)
  {
    id: 'bk-2',
    ticketNumber: '#MB-102',
    branchId: 'marjane',
    customerName: 'Nikoloz Tsereteli',
    customerPhone: '+995 577 234 567',
    isStudent: true,
    studentIdProof: 'TSU-2024-8192',
    allergies: 'Sensitive to alcohol aftershaves',
    barberId: 'b2',
    barberName: 'Barber #2',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 20,
    discountAmount: 9,
    price: 36,
    time: '11:00', // Expired past 10 min grace period
    source: 'WhatsApp',
    type: 'booking',
    status: 'Scheduled',
    createdAt: 'Today, 09:30',
    isNoShowGraceExpired: true,
  },
  // 3. Arrived (in lobby waiting)
  {
    id: 'bk-3',
    ticketNumber: '#MB-103',
    branchId: 'marjane',
    customerName: 'Levan Mchedlidze',
    customerPhone: '+995 591 345 678',
    isStudent: false,
    allergies: 'None',
    barberId: 'b1',
    barberName: 'Barber #1',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 0,
    discountAmount: 0,
    price: 45,
    time: '13:00',
    source: 'Phone',
    type: 'booking',
    status: 'Arrived',
    createdAt: 'Today, 11:00',
  },
  // 4. In Service (Chair Active)
  {
    id: 'bk-4',
    ticketNumber: '#MB-104',
    branchId: 'marjane',
    customerName: 'Sandro Javakhishvili',
    customerPhone: '+995 555 456 789',
    isStudent: true,
    studentIdProof: 'ILIAUNI-9921',
    allergies: 'Fragrance-sensitive beard oils',
    barberId: 'b3',
    barberName: 'Barber #3',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 20,
    discountAmount: 9,
    price: 36,
    time: '12:30',
    source: 'Direct Barber Booking',
    type: 'booking',
    status: 'In Service',
    createdAt: 'Today, 12:00',
  },
  // 5. Completed Cash
  {
    id: 'bk-5',
    ticketNumber: '#MB-105',
    branchId: 'marjane',
    customerName: 'Kote Bakradze',
    customerPhone: '+995 598 567 890',
    isStudent: false,
    allergies: 'None',
    barberId: 'b1',
    barberName: 'Barber #1',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 0,
    discountAmount: 0,
    price: 45,
    time: '10:00',
    source: 'Walk-in',
    type: 'walk-in',
    status: 'Completed',
    paymentMethod: 'cash',
    createdAt: 'Today, 10:00',
  },
  // 6. Completed Card (Student 20% discount applied: 45 - 9 = 36 GEL)
  {
    id: 'bk-6',
    ticketNumber: '#MB-106',
    branchId: 'marjane',
    customerName: 'Tornike Shengelia',
    customerPhone: '+995 579 678 901',
    isStudent: true,
    studentIdProof: 'SEU-STU-3301',
    allergies: 'None',
    barberId: 'b2',
    barberName: 'Barber #2',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 20,
    discountAmount: 9,
    price: 36,
    time: '11:30',
    source: 'Instagram',
    type: 'booking',
    status: 'Completed',
    paymentMethod: 'card',
    createdAt: 'Today, 11:30',
  },
  // 7. Cancelled
  {
    id: 'bk-7',
    ticketNumber: '#MB-107',
    branchId: 'marjane',
    customerName: 'Giorgi Eristavi',
    customerPhone: '+995 593 789 012',
    isStudent: false,
    allergies: 'None',
    barberId: 'b4',
    barberName: 'Barber #4',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 0,
    discountAmount: 0,
    price: 45,
    time: '15:00',
    source: 'Phone',
    type: 'booking',
    status: 'Cancelled',
    createdAt: 'Today, 08:45',
  },
  // 8. No-show (Grace period expired and marked as No-show)
  {
    id: 'bk-8',
    ticketNumber: '#MB-108',
    branchId: 'marjane',
    customerName: 'Vakhtang Gorgasali',
    customerPhone: '+995 574 890 123',
    isStudent: false,
    allergies: 'None',
    barberId: 'b5',
    barberName: 'Barber #5',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 0,
    discountAmount: 0,
    price: 45,
    time: '10:30',
    source: 'WhatsApp',
    type: 'booking',
    status: 'No-show',
    createdAt: 'Today, 09:10',
    isNoShowGraceExpired: true,
  },

  // -------------------------------------------------------------
  // Dighomi Appointments
  // -------------------------------------------------------------
  {
    id: 'bk-9',
    ticketNumber: '#DB-201',
    branchId: 'dighomi',
    customerName: 'Mikheil Saakadze',
    customerPhone: '+995 595 112 233',
    isStudent: false,
    allergies: 'None',
    barberId: 'b7',
    barberName: 'Barber #7',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 0,
    discountAmount: 0,
    price: 45,
    time: '11:00',
    source: 'Walk-in',
    type: 'walk-in',
    status: 'Completed',
    paymentMethod: 'cash',
    createdAt: 'Today, 11:00',
  },
  {
    id: 'bk-10',
    ticketNumber: '#DB-202',
    branchId: 'dighomi',
    customerName: 'Bacho Akhalaia',
    customerPhone: '+995 577 334 455',
    isStudent: true,
    studentIdProof: 'GAU-STU-1092',
    allergies: 'None',
    barberId: 'b8',
    barberName: 'Barber #8',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 20,
    discountAmount: 9,
    price: 36,
    time: '14:30',
    source: 'Phone',
    type: 'booking',
    status: 'Scheduled',
    createdAt: 'Today, 10:20',
  },

  // -------------------------------------------------------------
  // Saburtalo Appointments
  // -------------------------------------------------------------
  {
    id: 'bk-11',
    ticketNumber: '#SB-301',
    branchId: 'saburtalo',
    customerName: 'Ilia Chavchavadze',
    customerPhone: '+995 599 445 566',
    isStudent: false,
    allergies: 'None',
    barberId: 'b10',
    barberName: 'Barber #10',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 0,
    discountAmount: 0,
    price: 45,
    time: '12:00',
    source: 'Instagram',
    type: 'booking',
    status: 'Completed',
    paymentMethod: 'card',
    createdAt: 'Today, 12:00',
  },
  {
    id: 'bk-12',
    ticketNumber: '#SB-302',
    branchId: 'saburtalo',
    customerName: 'Shota Rustaveli',
    customerPhone: '+995 555 778 899',
    isStudent: true,
    studentIdProof: 'TSU-PHIL-001',
    allergies: 'None',
    barberId: 'b11',
    barberName: 'Barber #11',
    serviceId: 's1',
    serviceName: 'Hair + Beard',
    originalPrice: 45,
    discountPercent: 20,
    discountAmount: 9,
    price: 36,
    time: '16:00',
    source: 'WhatsApp',
    type: 'booking',
    status: 'Scheduled',
    createdAt: 'Today, 11:45',
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'c1',
    name: 'Davit Kipiani',
    phone: '+995 599 123 456',
    isStudent: false,
    allergies: 'None',
    totalVisits: 14,
    totalSpent: 630.00,
    lastVisit: '2026-09-15',
    preferredBarber: 'Barber #1',
    history: [
      { date: '2026-09-15', serviceName: 'Hair + Beard', barberName: 'Barber #1', amount: 45, paymentMethod: 'cash', type: 'booking' },
      { date: '2026-09-08', serviceName: 'Hair + Beard', barberName: 'Barber #1', amount: 45, paymentMethod: 'cash', type: 'booking' },
      { date: '2026-08-25', serviceName: 'Hair + Beard', barberName: 'Barber #1', amount: 45, paymentMethod: 'card', type: 'booking' },
    ],
  },
  {
    id: 'c2',
    name: 'Nikoloz Tsereteli',
    phone: '+995 577 234 567',
    isStudent: true,
    studentIdProof: 'TSU-2024-8192',
    allergies: 'Sensitive to alcohol aftershaves',
    totalVisits: 8,
    totalSpent: 288.00,
    lastVisit: '2026-09-15',
    preferredBarber: 'Barber #2',
    history: [
      { date: '2026-09-15', serviceName: 'Hair + Beard (Student 20% Off)', barberName: 'Barber #2', amount: 36, paymentMethod: 'card', type: 'booking' },
      { date: '2026-09-01', serviceName: 'Hair + Beard', barberName: 'Barber #2', amount: 36, paymentMethod: 'card', type: 'booking' },
    ],
  },
  {
    id: 'c3',
    name: 'Levan Mchedlidze',
    phone: '+995 591 345 678',
    isStudent: false,
    allergies: 'None',
    totalVisits: 19,
    totalSpent: 855.00,
    lastVisit: '2026-09-15',
    preferredBarber: 'Barber #1',
    history: [
      { date: '2026-09-15', serviceName: 'Hair + Beard', barberName: 'Barber #1', amount: 45, paymentMethod: 'card', type: 'booking' },
      { date: '2026-09-14', serviceName: 'Hydrofacial Deep Cleanse', barberName: 'Barber #1', amount: 80, paymentMethod: 'card', type: 'walk-in' },
    ],
  },
  {
    id: 'c4',
    name: 'Sandro Javakhishvili',
    phone: '+995 555 456 789',
    isStudent: true,
    studentIdProof: 'ILIAUNI-9921',
    allergies: 'Fragrance-sensitive beard oils',
    totalVisits: 5,
    totalSpent: 180.00,
    lastVisit: '2026-09-14',
    preferredBarber: 'Barber #3',
    history: [
      { date: '2026-09-14', serviceName: 'Hair + Beard (Student 20% Off)', barberName: 'Barber #3', amount: 36, paymentMethod: 'cash', type: 'booking' },
      { date: '2026-09-07', serviceName: 'Hair Cut & Styling', barberName: 'Barber #3', amount: 30, paymentMethod: 'cash', type: 'walk-in' },
    ],
  },
  {
    id: 'c5',
    name: 'Tornike Shengelia',
    phone: '+995 579 678 901',
    isStudent: true,
    studentIdProof: 'SEU-STU-3301',
    allergies: 'None',
    totalVisits: 6,
    totalSpent: 216.00,
    lastVisit: '2026-09-14',
    preferredBarber: 'Barber #2',
    history: [
      { date: '2026-09-14', serviceName: 'Hair + Beard (Student 20% Off)', barberName: 'Barber #2', amount: 36, paymentMethod: 'card', type: 'booking' },
    ],
  },
  {
    id: 'c6',
    name: 'George Bagrationi',
    phone: '+995 593 881 234',
    isStudent: false,
    allergies: 'None',
    totalVisits: 11,
    totalSpent: 520.00,
    lastVisit: '2026-09-12',
    preferredBarber: 'Barber #4',
    history: [
      { date: '2026-09-12', serviceName: 'Royal Shave & Face Treatment', barberName: 'Barber #4', amount: 75, paymentMethod: 'card', type: 'booking' },
      { date: '2026-08-28', serviceName: 'Hair + Beard', barberName: 'Barber #4', amount: 45, paymentMethod: 'card', type: 'booking' },
    ],
  },
  {
    id: 'c7',
    name: 'Irakli Kobakhidze',
    phone: '+995 558 776 543',
    isStudent: false,
    allergies: 'Prone to clipper rash on neckline',
    totalVisits: 7,
    totalSpent: 315.00,
    lastVisit: '2026-09-10',
    preferredBarber: 'Barber #5',
    history: [
      { date: '2026-09-10', serviceName: 'Classic Scissor Cut', barberName: 'Barber #5', amount: 40, paymentMethod: 'cash', type: 'booking' },
    ],
  },
  {
    id: 'c8',
    name: 'Luka Beridze',
    phone: '+995 571 332 119',
    isStudent: true,
    studentIdProof: 'GTU-9021-ENG',
    allergies: 'None',
    totalVisits: 4,
    totalSpent: 144.00,
    lastVisit: '2026-09-05',
    preferredBarber: 'Barber #6',
    history: [
      { date: '2026-09-05', serviceName: 'Hair + Beard (Student 20% Off)', barberName: 'Barber #6', amount: 36, paymentMethod: 'cash', type: 'walk-in' },
    ],
  },
  {
    id: 'c9',
    name: 'Vakhtang Gorgasali',
    phone: '+995 599 001 928',
    isStudent: false,
    allergies: 'None',
    totalVisits: 22,
    totalSpent: 1150.00,
    lastVisit: '2026-08-29',
    preferredBarber: 'Barber #1',
    history: [
      { date: '2026-08-29', serviceName: 'Master VIP Styling Package', barberName: 'Barber #1', amount: 95, paymentMethod: 'card', type: 'booking' },
    ],
  }
];

export const INITIAL_EXPENSES: Expense[] = [
  { 
    id: 'e1', 
    branchId: 'marjane', 
    category: 'Operational', 
    title: 'Barbicide Restock & Neck Strips', 
    amount: 45.00, 
    date: 'Today',
    description: 'Sterilization solution and sanitary rolls for 6 chairs',
    paymentSource: 'cash_drawer',
    receiptNumber: 'INV-2026-9012',
    allocatedBarberName: 'General Shop (All Staff)',
    createdAt: 'Today, 09:15'
  },
  { 
    id: 'e2', 
    branchId: 'marjane', 
    category: 'Customer-related', 
    title: 'Italian Espresso Beans & Mineral Water', 
    amount: 38.50, 
    date: 'Today',
    description: 'Complimentary beverages served to waiting lounge clients',
    paymentSource: 'cash_drawer',
    receiptNumber: 'INV-2026-9014',
    allocatedBarberName: 'General Shop (All Staff)',
    createdAt: 'Today, 10:00'
  },
  { 
    id: 'e3', 
    branchId: 'marjane', 
    category: 'Business', 
    title: 'Shop Internet & Terminal Gateway Fee', 
    amount: 60.00, 
    date: 'Today',
    description: 'High-speed fiber connectivity for POS systems',
    paymentSource: 'bank_transfer',
    receiptNumber: 'INV-2026-8831',
    allocatedBarberName: 'General Shop (All Staff)',
    createdAt: 'Today, 08:30'
  },
  { 
    id: 'e4', 
    branchId: 'marjane', 
    category: 'Barber/worker', 
    title: 'Wahl Clipper Blade Replacements', 
    amount: 55.00, 
    date: 'Today',
    description: 'Ceramic blade sets distributed to stations',
    paymentSource: 'cash_drawer',
    receiptNumber: 'INV-2026-9022',
    allocatedBarberId: 'b1',
    allocatedBarberName: 'Barber #1',
    createdAt: 'Today, 11:20'
  },
  { 
    id: 'e5', 
    branchId: 'dighomi', 
    category: 'Operational', 
    title: 'Paper Towels & Cleaning Detergents', 
    amount: 25.00, 
    date: 'Today',
    description: 'Station hygiene and floor sanitation',
    paymentSource: 'cash_drawer',
    receiptNumber: 'INV-2026-9030',
    allocatedBarberName: 'General Shop (All Staff)',
    createdAt: 'Today, 10:45'
  },
  { 
    id: 'e6', 
    branchId: 'saburtalo', 
    category: 'Customer-related', 
    title: 'Lounge Beverage Re-stock', 
    amount: 30.00, 
    date: 'Today',
    description: 'Sparkling water & coffee pods',
    paymentSource: 'cash_drawer',
    receiptNumber: 'INV-2026-9041',
    allocatedBarberName: 'General Shop (All Staff)',
    createdAt: 'Today, 11:00'
  },
];

export const INITIAL_WITHDRAWALS: BarberWithdrawal[] = [
  { 
    id: 'w1', 
    branchId: 'marjane', 
    barberId: 'b1', 
    barberName: 'Barber #1', 
    amount: 50.00, 
    date: 'Today', 
    reason: 'Midday Personal Cash Advance' 
  },
  { 
    id: 'w2', 
    branchId: 'marjane', 
    barberId: 'b2', 
    barberName: 'Barber #2', 
    amount: 80.00, 
    date: 'Today', 
    reason: 'Fuel & Commute Cash Advance' 
  },
  { 
    id: 'w3', 
    branchId: 'dighomi', 
    barberId: 'b7', 
    barberName: 'Barber #7', 
    amount: 40.00, 
    date: 'Today', 
    reason: 'Daily Lunch & Transit' 
  },
  { 
    id: 'w4', 
    branchId: 'saburtalo', 
    barberId: 'b10', 
    barberName: 'Barber #10', 
    amount: 60.00, 
    date: 'Today', 
    reason: 'Equipment Maintenance Advance' 
  },
];
